#!/usr/bin/env python
#
# Yocto Build Server Stop Script
# Elizabeth Flanagan <elizabeth.flanagan@intel.com>
#
##
# Copyright (C) 2011-2012 Intel Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import os, sys, optparse, subprocess, signal, time
from socket import gethostname

usage  = """%prog [options] controller|worker|both   

Stop a yocto buildbot autobuilder instance.
"""

parser = optparse.OptionParser(usage=usage)
options, args = parser.parse_args( sys.argv )

if len(args) != 2 or (sys.argv[1] != "both" and sys.argv[1] != "controller" and sys.argv[1] != "worker") :
    parser.error("""
    You must specify if you wish to stop controller, worker or both. 
   
    """ + usage )

AB_BASE=os.path.dirname(os.path.abspath(sys.argv[0]))

if sys.argv[1] == "controller" or sys.argv[1] == "both":
    os.chdir(os.path.join(AB_BASE, "yocto-controller"))
    subprocess.call(["make", "stop"])
    os.chdir(AB_BASE)

if sys.argv[1] == "worker" or sys.argv[1] == "both":
    os.chdir(os.path.join(AB_BASE, "yocto-worker"))
    subprocess.call(["make", "stop"])
    os.chdir(AB_BASE)
    if os.path.exists('/tmp/.buildworker-janitor') and os.path.isfile('/tmp/.buildworker-janitor'):
        print("A prior PID file exists. Attempting to kill.")
        with open('/tmp/.buildworker-janitor', 'r') as f:
            pid=f.readline()
        try: 
            os.kill(int(pid), signal.SIGKILL)
            # We need to sleep for a second or two just to give the SIGKILL time
            time.sleep(2)
        except OSError as ex:
            print("""We weren't able to kill the prior buildworker-janitor. Trying again.""")
            pass
        # Check if the process that we killed is alive.
        try: 
           os.kill(int(pid), 0)
           raise Exception("""wasn't able to kill the process 
                              HINT:use signal.SIGKILL or signal.SIGABORT""")
        except OSError as ex:
           pass
    elif os.path.exists('/tmp/.buildworker-janitor') and not os.path.isfile('/tmp/.buildworker-janitor'):
        raise Exception("""/tmp/.buildworker-janitor is a director. remove it to continue.""")
    try:
        os.unlink('/tmp/.buildworker-janitor')
    except:
        pass

